#!/bin/sh

gksudo mount /dev/sda2 /media/WINDOWS
idesk &
GTK2_RC_FILES=/home/phil/.icewm/trayicon.rc gnome-volume-conrtol-applet &
GTK2_RC_FILES=/home/phil/.icewm/trayicon.rc nm-applet &
/home/phil/.fehbg
